apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest
          command: ['sh', '-c', 'until pg_isready -h postgres-svc.default.svc.cluster.local -p 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: todo-backend
          image: TODOBACKEND/IMAGE
          resources:
            limits:
              cpu: "10m"
              memory: "100Mi"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
            - name: NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: namespace-config
                  key: NAMESPACE