apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-project
resources:
  - ../../base
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
patches:
  - path: frontend-svc-patch.yaml
  - path: todo-backend-svc-patch.yaml
configMapGenerator:
  - name: namespace-config
    literals:
      - NAMESPACE=local-project