apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: postgres-password
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ed0WXZ0YkgIPXjdgs39Hgg==,iv:QDNjQMOg3QdjoxyUlBiulM/vOV19B/5AZnAIDtt1sQM=,tag:y9cgLIphi49UXEdMYlOpMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mwdkusww9kcmlrtnj90n3y593w23cmaq5egf4fh622rm8hha94q42tcfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUGFPTkJzSmtpQko4UTJC
            dVhWK2JwQWhIUUM2TEQ2a0FyclhiNWdDaUZvClJ6c0htTDdqcG81MmIzMTZueW9k
            RzVUNTVoSHYxbVNNVlNGS3NHU25VQVUKLS0tIGVOQVdXZkk3UGpuOExiU2JGT1Rj
            S2d3c1E0S29jTmJ3L2JaREYvUG5zYnMK8B3Fn3SJKsJGDKeaZ5EM2kckPZUjYuGQ
            cPBY8Lm2tPxjn2F5YiLO5HhKhXAdnMy7ctkf1sfsLYKgwf53GNZnAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T09:58:21Z"
    mac: ENC[AES256_GCM,data:8B5IeaSaZr/EUYMXk8aUHm9ieqPUIdDWpLj2txcqRbqbA2odCmBzJozVjoqsixNqBGzC+Z4EKN6pyRtuToKskgNLIsz+h4jB/uxAV8h6tMgV1bQsD1FBocFebvkl3kbFoQAQnysUHm5AMozDpy7MojR5T1z9UQz/16fCXTFgepA=,iv:P02qn05R/G63JIbAXu6La/hrrp344lr4j69Y5AD9GBw=,tag:KKwg6RwdygCWX7farbngjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
