apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ping-pong-dep.yaml
  - log-output-dep.yaml
  - postgres.yaml
  - configmap.yaml
  - secret.yaml
  - ping-pong-svc.yaml
  - log-output-svc.yaml
  - ingress.yaml
  
images:
  - name: PINGPONG/IMAGE
    newName: oskuh/ping-pong-app:latest
  - name: TIMESTAMPGENERATOR/IMAGE
    newName: oskuh/timestamp-generator-app:latest
  - name: TIMESTAMPOUTPUT/IMAGE
    newName: oskuh/timestamp-output-app:latest
