apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/ping-pong-dep.yaml
  - manifests/log-output-dep.yaml
  - manifests/postgres.yaml
  - manifests/configmap.yaml
  - manifests/secret.yaml
  - manifests/ping-pong-svc.yaml
  - manifests/log-output-svc.yaml
  - manifests/ingress.yaml
  
images:
  - name: PINGPONG/IMAGE
    newName: oskuh/ping-pong-app:latest
  - name: TIMESTAMPGENERATOR/IMAGE
    newName: oskuh/timestamp-generator-app:latest
  - name: TIMESTAMPOUTPUT/IMAGE
    newName: oskuh/timestamp-output-app:latest
