apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/postgres.yaml
  - manifests/secret.yaml
  - manifests/frontend-dep.yaml
  - manifests/todo-backend-dep.yaml
  - manifests/frontend-svc.yaml
  - manifests/todo-backend-svc.yaml
  - manifests/ingress.yaml
  - manifests/cronjob.yaml
  
images:
  - name: IMAGEFINDER/IMAGE
    newName: oskuh/image-finder-app:latest
  - name: PROJECTOUTPUT/IMAGE
    newName: oskuh/project-output-app:latest
  - name: TODOBACKEND/IMAGE
    newName: oskuh/todo-backend-app:latest
