apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: image-claim
spec:
  storageClassName: p-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi