name: Delete namespace

on:
  delete:
    branches:
      - '*'

jobs:
  delete-namespace:
    name: Delete namespace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
        
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
      
      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
      
      - name: Set namespace variable
        run: |
          if [ "${{ github.event.ref }}" = "main" ]; then
            NAMESPACE="default"
          else
            NAMESPACE="${{ github.event.ref }}"
          fi
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
        
      - name: Delete namespace
        run: kubectl delete namespace $NAMESPACE
        env:
          NAMESPACE: ${{ env.NAMESPACE }}
